name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout with tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: get version information
        run: |
          echo "JSR_VERSION=$(jq -rM '.version' jsr.json)" >> $GITHUB_OUTPUT
          echo ${{ github.ref_name }} | sed -Ee 's#.*[^0-9]+([0-9]+\.[0-9]+\.[0-9])$#TAG_VERSION=\1#' >> $GITHUB_OUTPUT

      - name: publish a package to JSR if both versions are same
        if: "$JSR_VERSION" == "$TAG_VERSION"
        run: npx jsr publish
