name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: checkout with tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: get version information from jsr.json
        id: vars
        run: |
          echo "JSR_VERSION=$(jq -rM '.version' jsr.json)" >> $GITHUB_OUTPUT
          echo ${{ github.ref_name }} | sed -Ee 's#([0-9]+\.[0-9]+\.[0-9])$# TAG_VERSION=\1#' | cut -d ' ' -f 2 >> $GITHUB_OUTPUT

      - name: if
        env:
          JSR_VERSION: ${{ steps.vars.outputs.JSR_VERSION }}
          TAG_VERSION: ${{ steps.vars.outputs.TAG_VERSION }}
        if: ${{ steps.vars.outputs.JSR_VERSION == steps.vars.outputs.TAG_VERSION }}
        run: npx jsr publish --config jsr.json
